name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  Job1:
    name: run tests
    runs-on: "ubuntu-latest"
    env:
      DATABASE_URL: ${{ env.DATABASE_URL }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test
